name: Test stamp

on: pull_request

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run custom action
        uses: ./
        with:
          path: ./